sudo: required
services:
  - docker

before_install:
  - docker build -t fo2shako/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fo2shako/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-523079191174"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"