version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/react/node_modules
      - .:/app/react
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/react/node_modules
      - .:/app/react
    command: ["npm", "run", "test"]